/**
 * Returns a stripped title string for podcast episode.
 * The stripped title is generated by removing episode numbers (preceded by a vertical bar or a hash symbol)
 * from the given title string and trimming any leading and trailing whitespace.
 *
 * @param title - The title string of the podcast episode.
 * @returns A stripped title string for podcast episode.
 *
 * @example
 *
 * generateGoodPodcastEpisodeTitles("Easy Communication & Technology | Episode #42");
 * // Returns "Easy Communication & Technology"
 */
export default function generateGoodPodcastEpisodeTitles(
  title: string,
): string {
  const regex = /(\|\s*|#)\s*\d+\s*$/g; // match episode numbers at the end of the title
  let stripped = title.replace(regex, ""); // remove any matches of the regex from the title

  const lastPipeIndex = stripped.lastIndexOf("|");
  if (lastPipeIndex !== -1) {
    stripped = stripped.slice(0, Math.max(0, lastPipeIndex));
  }

  return stripped.trim(); // remove leading and trailing whitespace
}
