version: "3.8"
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - backend

  graphql-engine:
    image: hasura/graphql-engine:v2.35.1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
