/**
 * Returns a URL-friendly slug generated from the given title string.
 * The slug is generated by converting the title to lowercase,
 * replacing spaces with hyphens, and removing any non-alphanumeric
 * characters (except hyphens).
 *
 * @param title - The title string to generate a slug from.
 * @returns A URL-friendly slug generated from the given title string.
 *
 * @example
 *
 * generateSlugFromTitle("Easy Communication & Technology");
 * "easy-communication-technology"
 */
export default function generateSlugFromTitle(title: string): string {
  let slug: string = title.toLowerCase().replace(/\s+/g, "-");
  slug = slug.replace(/[^a-z0-9-]/g, "");
  return slug;
}
